# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/zenpy-garden',
                'doc_host': 'https://shawnemhe.github.io',
                'git_url': 'https://github.com/shawnemhe/zenpy-garden',
                'lib_path': 'zpgarden'},
  'syms': {'zpgarden.core': {'zpgarden.core.foo': ('core.html#foo', 'zpgarden/core.py')}}}
