"""FastHTML wrappers for Zendesk Garden CSS components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_components.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01_components.ipynb 2
from fasthtml.common import *
from .core import *

# %% ../nbs/01_components.ipynb 6
mk_compfn('c-anchor', 'A')

# %% ../nbs/01_components.ipynb 14
mk_compfn('c-avatar', 'Figure')
mk_compfn('c-avatar__txt', 'Span', 'AvatarText')
