"""FastHTML wrappers for Zendesk Garden CSS components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_components.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01_components.ipynb 2
from fasthtml.common import *
from .core import *

# %% ../nbs/01_components.ipynb 6
mk_compfn('c-anchor', 'A')

# %% ../nbs/01_components.ipynb 14
mk_compfn('c-avatar', 'Figure')
mk_compfn('c-avatar__txt', 'Span')

# %% ../nbs/01_components.ipynb 27
mk_compfn('c-btn', 'Button')

# %% ../nbs/01_components.ipynb 43
mk_compfn('c-field', 'Div')
mk_compfn('c-field__label', 'Label')
mk_compfn('c-field__hint', 'Div')
mk_compfn('c-field__input', 'Input')
mk_compfn('c-field__input', 'Textarea', 'Textarea', xcls='c-field__input--area')
mk_compfn('c-field__input', 'Select', 'Select', xcls='c-field__input--select')
mk_compfn('c-field__message', 'Div')
mk_compfn('c-field__checkbox', 'Input', 'Checkbox', type='checkbox')
mk_compfn('c-field__radio', 'Input', 'Radio', type='radio')
