# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/zenpy-garden',
                'doc_host': 'https://shawnemhe.github.io',
                'git_url': 'https://github.com/shawnemhe/zenpy-garden',
                'lib_path': 'zenpy_garden'},
  'syms': {'zenpy_garden.core': {'zenpy_garden.core.foo': ('core.html#foo', 'zenpy_garden/core.py')}}}
